### ISSUE TITLE
connection to Mosquitto fails with "Socket error on client <unknown>"

### ISSUE THREAD

**Issue by klaus-hildner** [njh/ruby-em-mqtt#10]
Hi all,

I am running the mqtt-mochad-bridge.rb between Mosquitto 1.4.1 / MQTT and mochad.
In the MQTT broker window, upon starting the bridge, I get "New connection from 127.0.0.1 on port 1883" and an instant "Socket error on client <unknown>, disconnecting.".

I traced my way down with (out)puts into the em-mqtt 0.0.3 client_connection.rb
and see that the ID is generated randomly upon connection.
My desperately hardcoded value ID99 did of course not help, nor did increasing timeouts.

The screenshot first shows 3 clients (all subscribers) connect successfully and being recognised by ID.
But when starting the bridge, it is instantly disconnected again.

![2015-04-19_13h29_14](https://cloud.githubusercontent.com/assets/11913000/7219325/5efe3a56-e69a-11e4-874b-0b21cc66d1e9.png)

All defaults, i. e. all running on localhost (a Raspi 2B), MQTT listening to port 1883, mochad to port 1099, no encryption.
The ruby process runs as root.
The two of the clients connect with default protocol, one client with tcp://.
best reagrds

Klaus

**Comment by klaus-hildner** [comment]
All defaults, i. e. all running on localhost (a Raspi 2B), MQTT listening to port 1883, mochad to port 1099, no encryption.
The ruby process runs as root.
The two of the clients connect with default protocol, one client with tcp://.

**Comment by njh** [comment]
Hello Klaus,

My 'mqtt-mochad-bridge' project was never completed and I can't remember if I ever actually got it working.

Socket errors with em-mqtt are usually because something else is going wrong, an exception is being raised and the connection to the broker closed. But EventMachine (I think the Deferrable class) makes it hard to find out what the original problem was.

nick.

**Comment by klaus-hildner** [comment]
Thanks Nick!

**Comment by klaus-hildner** [comment]
Hi Nick,

just in case - I have shared my code:
https://github.com/klaus-hildner/mochad2mqtt

Unfortunately, lots is hardcoded. :-(

best regards

Klaus
