### ISSUE TITLE
Is it possible to separate instantiation process from connect process? 

### ISSUE THREAD

**Issue by RickCarlino** [njh/ruby-em-mqtt#14]
Hi,

I am transitioning an IoT app over to `ruby-em-mqtt` and had a question about the API that this gem exposes.

Right now, I am able to connect to a broker like this:

```ruby
  client = EventMachine::MQTT::ClientConnection.connect(
    host: 'localhost',
    username: 'test123@test.com',
    password: 'password123'
  )
```

Unfortunately, this makes it hard to separate client instantiation logic from client connection logic. Is it possible to do something like this?

```ruby
# PSEUDO CODE DOES NOT ACTUALLY WORK LIKE THIS
  client = EventMachine::MQTT::ClientConnection.new(
    host: 'localhost',
    username: 'test123@test.com',
    password: 'password123'
  )
  client.connect # MQTT::ClientConnection currently does not implement this.
```

Connecting in the manner shown above makes it a little bit easier to test and separate concerns. I could not find a `connect` method at the instance level, though.

Is it possible to connect to an MQTT broker in the manner shown above?

Thanks for all your work on the gem. Has been very reliable and easy to use.

**Comment by njh** [comment]
Hello,

I agree that separating instantiation from connection would be very desirable.
I can't remember why it is this way, I suspect it relates to the underlying classes that it subclasses.

Patches/Pull Requests very welcome :smiley: 

nick.

**Comment by RickCarlino** [comment]
Thanks Nick! I might have some time in the coming weeks to patch it, schedule allowing.
