### ISSUE TITLE
Please add some means to let us know the lost of connection.

### ISSUE THREAD

**Issue by hxcan** [njh/ruby-em-mqtt#17]
Currently, we have no means to handle the lost of connection .
When the connection broke unexpectedly, the whole ruby script just crashed. 

Please add some means to catch this kind of exception, so that we can reconnect manually in our code.

See the attachment log, when connection was lost, the whole process just crashed.
[connectionLostCrash.txt](https://github.com/njh/ruby-em-mqtt/files/258954/connectionLostCrash.txt)

**Comment by njh** [comment]
Your log file shows a Segmentation fault.
This is a bug in Event Machine, it is not something that can be caught in ruby / ruby-em-mqtt.

```unbind``` should be called and an exception thrown when the connection is lost.

**Comment by pgouv** [comment]
@njh Why raising a global error though? It makes reconnecting/etc harder

**Comment by njh** [comment]
EventMachine uses event processing rather than threads to handle multiple connections (a bit like node.js) - everything runs in the main thread.

I am going to lock this conversation because it doesn't seem related to the original issue.
