### ISSUE TITLE
Incompatible with mqtt 0.2.0 gem?

### ISSUE THREAD

**Issue by themilkman** [njh/ruby-em-mqtt#8]
Hi,

since I updated my bundle and your new release of the mqtt gem came in I get the following error:
```
<..>bundle/ruby/2.1.0/gems/em-mqtt-0.0.3/lib/em/mqtt/client_connection.rb:63:in `unbind': Connection to server lost (MQTT::NotConnectedException)
  from <..>bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1440:in `event_callback'
  from <..>bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:194:in `release_machine'
  from <..>bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:194:in `ensure in run'
  from <..>bundle/ruby/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:218:in `run'
```

My code is:

```
EventMachine.run do
  Improve::ClientConnection.connect(APP_CONFIG[:mqtt][:hostname]) do |c|

    c.subscribe('my_topic')

    c.receive_callback do |message|
      # ...
    end
  end
end
```

Do you have any idea why this happens with the new version? Thanks in advance!

Cheers
Erik

**Comment by mkarliner** [comment]
Bump. Just tried the gem. I get the same error.

**Comment by njh** [comment]
This is working for me:

    #!/usr/bin/env ruby

    require 'rubygems'
    require 'em/mqtt'

    module Improve
      class ClientConnection < EventMachine::MQTT::ClientConnection

        def post_init
          super
          @username = 'myuser'
          @password = 'mypass'
        end

        def connection_completed
          # Protocol name and version
          packet = MQTT::Packet::Connect.new(
            :clean_session  => @clean_session,
            :keep_alive   => @keep_alive,
            :client_id    => @client_id,
            :username     => @username,
            :password     => @password
          )
          send_packet(packet)
          @state = :connect_sent
        end

      end
    end


    EventMachine.run do
      Improve::ClientConnection.connect('localhost') do |c|

        c.subscribe('test')

        c.receive_callback do |message|
          p message
        end
      end
    end

But I will get proper username/password support added in #4

**Comment by mkarliner** [comment]
After a little investigation, I've found the issue. Mosquitto 1.4 (just released) takes exception to being given username and passwd when it has open access. This issue does not appear with the 1.3 release.
I don't suggest reopening this, but you might want to put something in the README to avoid more issues  being raised.

**Comment by njh** [comment]
Ok. That is good to know.

I think the biggest problem is that EventMachine conceals the original error/exception and all you see is that connection getting dropped.

**Comment by mkarliner** [comment]
There wasn't much on the mosquitto side, event though I had
all the taps turned on for debugging from a different problem
last week. I found it by trial and error.

Mike

**Comment by njh** [comment]
I have found that this makes diagnosing problems much easier:

    EventMachine::error_handler { |e| puts "#{e}: #{e.backtrace.first}" }
